### ISSUE TITLE
Remove database password

### ISSUE THREAD

**Issue by Enootikin** [Rocky43007/Rockibot#13]
commands:
[logs](https://github.com/Rocky43007/Rockibot/blob/c9fa116c1ef24db62cb94729cb0ca0235363db5a/commands/moderation/logs.js)
[suggestchannel](https://github.com/Rocky43007/Rockibot/blob/c9fa116c1ef24db62cb94729cb0ca0235363db5a/commands/suggestions/suggestchannel.js)
[consider](https://github.com/Rocky43007/Rockibot/blob/c9fa116c1ef24db62cb94729cb0ca0235363db5a/commands/suggestions/consider.js)
[deny](https://github.com/Rocky43007/Rockibot/blob/c9fa116c1ef24db62cb94729cb0ca0235363db5a/commands/suggestions/deny.js)
[impliment](https://github.com/Rocky43007/Rockibot/blob/c9fa116c1ef24db62cb94729cb0ca0235363db5a/commands/suggestions/impliment.js)
[ban](https://github.com/Rocky43007/Rockibot/blob/235cba79622d7c481afb106ed5c83301ab72e00d/commands/moderation/ban.js)
[kick](https://github.com/Rocky43007/Rockibot/blob/235cba79622d7c481afb106ed5c83301ab72e00d/commands/moderation/kick.js)
[purge](https://github.com/Rocky43007/Rockibot/blob/235cba79622d7c481afb106ed5c83301ab72e00d/commands/moderation/purge.js)
[approve](https://github.com/Rocky43007/Rockibot/blob/5950d3547840fb90dc479cb69728ce9d4f4810b9/commands/suggestions/approve.js)
[suggest](https://github.com/Rocky43007/Rockibot/blob/d0f879c949227fa7f5d0a56c0efe08803aa32a8b/commands/suggestions/suggest.js)
[mute](https://github.com/Rocky43007/Rockibot/blob/235cba79622d7c481afb106ed5c83301ab72e00d/commands/moderation/mute.js)
[unmute](https://github.com/Rocky43007/Rockibot/blob/235cba79622d7c481afb106ed5c83301ab72e00d/commands/moderation/unmute.js)
[unwarn](https://github.com/Rocky43007/Rockibot/blob/235cba79622d7c481afb106ed5c83301ab72e00d/commands/moderation/unwarn.js)
[warn](https://github.com/Rocky43007/Rockibot/blob/235cba79622d7c481afb106ed5c83301ab72e00d/commands/moderation/warn.js)

**Comment by Rocky43007** [comment]
Hi! I'm actually working on this right now. But for some reason, the config file can't be seen by the commands. But thanks again for putting it here!
